2023-01-01 22:43:18,039 db_manager INFO: DB create_all called
2023-01-01 22:43:18,039 db_manager ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-01 22:48:42,601 db_manager INFO: DB create_all called
2023-01-01 22:49:04,884 db_manager INFO: DB create_all called
2023-01-01 22:49:04,886 db_manager_task INFO:  register_task in DB ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-01 22:49:04,886 db_manager_task INFO: {'alias': 'default', 'type': '0'}
2023-01-01 22:49:04,886 db_manager_task INFO: default
2023-01-01 22:49:04,889 db_manager_task ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-01 22:54:48,801 db_manager INFO: DB create_all called
2023-01-01 22:54:48,803 db_manager_task INFO:  register_task in DB ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-01 22:54:48,803 db_manager_task INFO: {'alias': 'default', 'type': '0'}
2023-01-01 22:54:48,803 db_manager_task INFO: default
2023-01-01 22:54:48,807 db_manager_task ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-01 23:09:45,823 db_manager INFO: DB create_all called
2023-01-01 23:09:45,825 db_manager_task INFO:  register_task in DB ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-01 23:09:45,825 db_manager_task INFO: {'alias': 'default', 'type': '0'}
2023-01-01 23:09:45,825 db_manager_task INFO: default
2023-01-01 23:09:45,831 db_manager_task ERROR: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT "TASK_T"."ID" AS "TASK_T_ID", "TASK_T"."Alias" AS "TASK_T_Alias", "TASK_T"."Type" AS "TASK_T_Type", "TASK_T"."CreatedTime" AS "TASK_T_CreatedTime" 
FROM "TASK_T" 
WHERE "TASK_T"."ID" = ?]
[parameters: (UUID('e918b3ca-7846-3104-8c4d-feb016a9e618'),)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
2023-01-01 23:09:45,831 db_manager_task INFO: regist Task ID:e918b3ca-7846-3104-8c4d-feb016a9e618
2023-01-01 23:15:34,251 db_manager INFO: DB create_all called
2023-01-01 23:15:34,253 db_manager_task INFO:  register_task in DB ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-01 23:15:34,253 db_manager_task INFO: {'alias': 'default', 'type': '0'}
2023-01-01 23:15:34,253 db_manager_task INFO: default
2023-01-01 23:15:34,259 db_manager_task ERROR: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT "TASK_T"."ID" AS "TASK_T_ID", "TASK_T"."Alias" AS "TASK_T_Alias", "TASK_T"."Type" AS "TASK_T_Type", "TASK_T"."CreatedTime" AS "TASK_T_CreatedTime" 
FROM "TASK_T" 
WHERE "TASK_T"."ID" = ?]
[parameters: (UUID('e918b3ca-7846-3104-8c4d-feb016a9e618'),)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
2023-01-01 23:15:34,260 db_manager_task INFO: regist Task ID:e918b3ca-7846-3104-8c4d-feb016a9e618
2023-01-01 23:17:35,328 db_manager INFO: DB create_all called
2023-01-01 23:17:35,330 db_manager_task INFO:  register_task in DB ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-01 23:17:35,330 db_manager_task INFO: {'alias': 'default', 'type': '0'}
2023-01-01 23:17:35,330 db_manager_task INFO: default
2023-01-01 23:17:35,336 db_manager_task ERROR: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT "TASK_T"."ID" AS "TASK_T_ID", "TASK_T"."Alias" AS "TASK_T_Alias", "TASK_T"."Type" AS "TASK_T_Type", "TASK_T"."CreatedTime" AS "TASK_T_CreatedTime" 
FROM "TASK_T" 
WHERE "TASK_T"."ID" = ?]
[parameters: (UUID('e918b3ca-7846-3104-8c4d-feb016a9e618'),)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
2023-01-01 23:17:35,336 db_manager_task INFO: regist Task ID:e918b3ca-7846-3104-8c4d-feb016a9e618
2023-01-01 23:23:12,667 db_manager INFO: DB create_all called
2023-01-01 23:23:12,669 db_manager_task INFO:  register_task in DB ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-01 23:23:12,669 db_manager_task INFO: {'alias': 'default', 'type': '0'}
2023-01-01 23:23:12,669 db_manager_task INFO: default
2023-01-01 23:23:12,674 db_manager_task ERROR: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT "TASK_T"."ID" AS "TASK_T_ID", "TASK_T"."Alias" AS "TASK_T_Alias", "TASK_T"."Type" AS "TASK_T_Type", "TASK_T"."CreatedTime" AS "TASK_T_CreatedTime" 
FROM "TASK_T" 
WHERE "TASK_T"."ID" = ?]
[parameters: (UUID('e918b3ca-7846-3104-8c4d-feb016a9e618'),)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
2023-01-01 23:23:12,674 db_manager_task INFO: regist Task ID:e918b3ca-7846-3104-8c4d-feb016a9e618
2023-01-01 23:26:01,101 db_manager INFO: DB create_all called
2023-01-01 23:26:01,103 db_manager_task INFO:  register_task in DB ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-01 23:26:01,103 db_manager_task INFO: {'alias': 'default', 'type': '0'}
2023-01-01 23:26:01,103 db_manager_task INFO: default
2023-01-01 23:26:01,109 db_manager_task ERROR: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT "TASK_T"."ID" AS "TASK_T_ID", "TASK_T"."Alias" AS "TASK_T_Alias", "TASK_T"."Type" AS "TASK_T_Type", "TASK_T"."CreatedTime" AS "TASK_T_CreatedTime" 
FROM "TASK_T" 
WHERE "TASK_T"."ID" = ?]
[parameters: (UUID('e918b3ca-7846-3104-8c4d-feb016a9e618'),)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
2023-01-01 23:26:01,109 db_manager_task INFO: regist Task ID:e918b3ca-7846-3104-8c4d-feb016a9e618
2023-01-01 23:26:18,165 db_manager INFO: DB create_all called
2023-01-01 23:26:18,167 db_manager_task INFO:  register_task in DB ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-01 23:26:18,167 db_manager_task INFO: {'alias': 'default', 'type': '0'}
2023-01-01 23:26:18,167 db_manager_task INFO: default
2023-01-01 23:26:18,173 db_manager_task ERROR: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT "TASK_T"."ID" AS "TASK_T_ID", "TASK_T"."Alias" AS "TASK_T_Alias", "TASK_T"."Type" AS "TASK_T_Type", "TASK_T"."CreatedTime" AS "TASK_T_CreatedTime" 
FROM "TASK_T" 
WHERE "TASK_T"."ID" = ?]
[parameters: (UUID('e918b3ca-7846-3104-8c4d-feb016a9e618'),)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
2023-01-01 23:26:18,173 db_manager_task INFO: regist Task ID:e918b3ca-7846-3104-8c4d-feb016a9e618
2023-01-01 23:26:18,210 server INFO: CELERY CFG: server.config.cfg_celery_local
2023-01-01 23:40:10,540 db_manager INFO: DB create_all called
2023-01-01 23:40:10,542 db_manager_task INFO:  register_task in DB ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-01 23:40:10,542 db_manager_task INFO: {'alias': 'default', 'type': '0'}
2023-01-01 23:40:10,542 db_manager_task INFO: default
2023-01-01 23:40:10,547 db_manager_task ERROR: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT "TASK_T"."ID" AS "TASK_T_ID", "TASK_T"."Alias" AS "TASK_T_Alias", "TASK_T"."Type" AS "TASK_T_Type", "TASK_T"."CreatedTime" AS "TASK_T_CreatedTime" 
FROM "TASK_T" 
WHERE "TASK_T"."ID" = ?]
[parameters: (UUID('e918b3ca-7846-3104-8c4d-feb016a9e618'),)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
2023-01-01 23:40:10,548 db_manager_task INFO: regist Task ID:e918b3ca-7846-3104-8c4d-feb016a9e618
2023-01-01 23:48:31,346 db_manager INFO: DB create_all called
2023-01-01 23:48:31,348 db_manager_task INFO:  register_task in DB ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-01 23:48:31,348 db_manager_task INFO: {'alias': 'default', 'type': '0'}
2023-01-01 23:48:31,348 db_manager_task INFO: default
2023-01-01 23:48:31,354 db_manager_task ERROR: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT "TASK_T"."ID" AS "TASK_T_ID", "TASK_T"."Alias" AS "TASK_T_Alias", "TASK_T"."Type" AS "TASK_T_Type", "TASK_T"."CreatedTime" AS "TASK_T_CreatedTime" 
FROM "TASK_T" 
WHERE "TASK_T"."ID" = ?]
[parameters: (UUID('e918b3ca-7846-3104-8c4d-feb016a9e618'),)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
2023-01-01 23:48:31,354 db_manager_task INFO: regist Task ID:e918b3ca-7846-3104-8c4d-feb016a9e618
2023-01-02 00:04:23,687 db_manager INFO: DB create_all called
2023-01-02 00:04:23,689 db_manager_task INFO:  register_task in DB ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-02 00:04:23,690 db_manager_task INFO: {'alias': 'default', 'type': '0'}
2023-01-02 00:04:23,690 db_manager_task INFO: default
2023-01-02 00:04:23,695 db_manager_task ERROR: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT "TASK_T"."ID" AS "TASK_T_ID", "TASK_T"."Alias" AS "TASK_T_Alias", "TASK_T"."Type" AS "TASK_T_Type", "TASK_T"."CreatedTime" AS "TASK_T_CreatedTime" 
FROM "TASK_T" 
WHERE "TASK_T"."ID" = ?]
[parameters: (UUID('e918b3ca-7846-3104-8c4d-feb016a9e618'),)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
2023-01-02 00:04:23,695 db_manager_task INFO: regist Task ID:e918b3ca-7846-3104-8c4d-feb016a9e618
2023-01-02 00:06:32,601 db_manager INFO: DB create_all called
2023-01-02 00:06:32,603 db_manager_task INFO:  register_task in DB ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-02 00:06:32,603 db_manager_task INFO: {'alias': 'default', 'type': '0'}
2023-01-02 00:06:32,603 db_manager_task INFO: default
2023-01-02 00:06:32,608 db_manager_task ERROR: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT "TASK_T"."ID" AS "TASK_T_ID", "TASK_T"."Alias" AS "TASK_T_Alias", "TASK_T"."Type" AS "TASK_T_Type", "TASK_T"."CreatedTime" AS "TASK_T_CreatedTime" 
FROM "TASK_T" 
WHERE "TASK_T"."ID" = ?]
[parameters: (UUID('e918b3ca-7846-3104-8c4d-feb016a9e618'),)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
2023-01-02 00:06:32,608 db_manager_task INFO: regist Task ID:e918b3ca-7846-3104-8c4d-feb016a9e618
2023-01-02 00:08:13,336 db_manager INFO: DB create_all called
2023-01-02 00:08:13,338 db_manager_task INFO:  register_task in DB ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-02 00:08:13,338 db_manager_task INFO: {'alias': 'default', 'type': '0'}
2023-01-02 00:08:13,338 db_manager_task INFO: default
2023-01-02 00:08:13,343 db_manager_task ERROR: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT "TASK_T"."ID" AS "TASK_T_ID", "TASK_T"."Alias" AS "TASK_T_Alias", "TASK_T"."Type" AS "TASK_T_Type", "TASK_T"."CreatedTime" AS "TASK_T_CreatedTime" 
FROM "TASK_T" 
WHERE "TASK_T"."ID" = ?]
[parameters: (UUID('e918b3ca-7846-3104-8c4d-feb016a9e618'),)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
2023-01-02 00:08:13,343 db_manager_task INFO: regist Task ID:e918b3ca-7846-3104-8c4d-feb016a9e618
2023-01-02 00:15:44,334 db_manager INFO: DB create_all called
2023-01-02 00:15:44,336 db_manager_task INFO:  register_task in DB ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-02 00:15:44,336 db_manager_task INFO: {'alias': 'default', 'type': '0'}
2023-01-02 00:15:44,337 db_manager_task INFO: default
2023-01-02 00:15:44,342 db_manager_task ERROR: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT "TASK_T"."ID" AS "TASK_T_ID", "TASK_T"."Alias" AS "TASK_T_Alias", "TASK_T"."Type" AS "TASK_T_Type", "TASK_T"."CreatedTime" AS "TASK_T_CreatedTime" 
FROM "TASK_T" 
WHERE "TASK_T"."ID" = ?]
[parameters: (UUID('e918b3ca-7846-3104-8c4d-feb016a9e618'),)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
2023-01-02 00:15:44,342 db_manager_task INFO: regist Task ID:e918b3ca-7846-3104-8c4d-feb016a9e618
2023-01-02 00:15:44,766 server INFO: CELERY CFG: server.config.cfg_celery_local
2023-01-02 00:15:44,766 server INFO: Starting Flask Resource report Info...
2023-01-02 00:15:44,767 server INFO: Starting Flask App...
2023-01-02 00:15:54,769 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:15:54,773 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:16:04,773 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:16:04,773 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:16:14,779 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:16:14,781 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:16:24,784 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:16:24,785 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:16:34,790 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:16:34,791 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:16:44,773 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:16:44,778 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 00:16:44,778 task_statustimer ERROR: TIMER REPORT update DB Exception:Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:16:44,795 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:16:44,796 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:16:54,801 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:16:54,802 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:17:04,801 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:17:04,802 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:17:14,802 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:17:14,803 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:17:24,809 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:17:24,810 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:17:34,811 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:17:34,811 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:17:44,777 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:17:44,778 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 00:17:44,778 task_statustimer ERROR: TIMER REPORT update DB Exception:Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:17:44,814 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:17:44,814 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:17:54,819 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:17:54,820 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:18:04,820 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:18:04,821 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:18:14,826 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:18:14,826 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:18:24,831 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:18:24,832 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:18:34,835 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:18:34,837 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:18:44,783 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:18:44,784 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 00:18:44,784 task_statustimer ERROR: TIMER REPORT update DB Exception:Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:18:44,840 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:18:44,840 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:18:54,846 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:18:54,847 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:19:04,847 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:19:04,849 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:19:14,852 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:19:14,853 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:19:24,857 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:19:24,860 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:19:34,861 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:19:34,861 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:19:44,789 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:19:44,791 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 00:19:44,791 task_statustimer ERROR: TIMER REPORT update DB Exception:Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:19:44,863 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:19:44,864 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:19:54,869 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:19:54,871 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:20:04,878 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:20:04,878 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:20:14,879 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:20:14,880 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:20:24,886 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:20:24,887 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:20:34,891 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:20:34,892 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:20:44,794 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:20:44,795 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 00:20:44,795 task_statustimer ERROR: TIMER REPORT update DB Exception:Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:20:44,894 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:20:44,895 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:20:54,901 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:20:54,902 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:21:04,906 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:21:04,908 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:21:14,912 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:21:14,913 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:21:24,917 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:21:24,918 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:21:34,924 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:21:34,925 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:21:44,796 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:21:44,798 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 00:21:44,798 task_statustimer ERROR: TIMER REPORT update DB Exception:Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:21:44,929 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:21:44,930 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:21:54,935 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:21:54,937 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:22:04,940 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:22:04,942 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:22:14,945 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:22:14,946 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:22:24,951 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:22:24,952 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:22:34,956 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:22:34,957 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:22:44,802 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:22:44,804 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 00:22:44,804 task_statustimer ERROR: TIMER REPORT update DB Exception:Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:22:44,961 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:22:44,961 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:22:54,967 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:22:54,968 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:23:04,972 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:23:04,973 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:23:14,978 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:23:14,979 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:23:24,981 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:23:24,982 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:23:34,986 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:23:34,987 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:23:44,804 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:23:44,806 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 00:23:44,806 task_statustimer ERROR: TIMER REPORT update DB Exception:Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:23:44,990 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:23:44,992 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:23:54,996 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:23:54,997 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:24:05,000 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:24:05,000 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:24:15,007 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:24:15,009 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:24:25,009 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:24:25,011 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:24:35,018 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:24:35,019 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:24:44,808 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:24:44,809 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 00:24:44,810 task_statustimer ERROR: TIMER REPORT update DB Exception:Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:24:45,029 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:24:45,029 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:24:55,040 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:24:55,042 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:25:05,043 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:25:05,044 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:25:15,047 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:25:15,048 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:25:25,052 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:25:25,052 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:25:35,055 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:25:35,056 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:25:44,816 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:25:44,817 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 00:25:44,817 task_statustimer ERROR: TIMER REPORT update DB Exception:Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:25:45,059 db_manager_report ERROR: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2023-01-02 00:25:45,059 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 00:37:17,540 db_manager INFO: DB create_all called
2023-01-02 00:37:17,541 db_manager_task INFO:  register_task in DB ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-02 00:37:17,542 db_manager_task INFO: {'alias': 'default', 'type': '0'}
2023-01-02 00:37:17,542 db_manager_task INFO: default
2023-01-02 00:37:17,547 db_manager_task ERROR: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT "TASK_T"."ID" AS "TASK_T_ID", "TASK_T"."Alias" AS "TASK_T_Alias", "TASK_T"."Type" AS "TASK_T_Type", "TASK_T"."CreatedTime" AS "TASK_T_CreatedTime" 
FROM "TASK_T" 
WHERE "TASK_T"."ID" = ?]
[parameters: (UUID('e918b3ca-7846-3104-8c4d-feb016a9e618'),)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
2023-01-02 00:37:17,547 db_manager_task INFO: regist Task ID:e918b3ca-7846-3104-8c4d-feb016a9e618
2023-01-02 00:37:17,657 server INFO: CELERY CFG: server.config.cfg_celery_local
2023-01-02 00:37:17,657 server INFO: Starting Flask Resource report Info...
2023-01-02 00:37:17,658 server INFO: Starting Flask App...
2023-01-02 00:37:48,497 db_manager INFO: DB create_all called
2023-01-02 00:37:48,499 db_manager_task INFO:  register_task in DB ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-02 00:37:48,500 db_manager_task INFO: {'alias': 'default', 'type': '0'}
2023-01-02 00:37:48,500 db_manager_task INFO: default
2023-01-02 00:37:48,505 db_manager_task ERROR: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT "TASK_T"."ID" AS "TASK_T_ID", "TASK_T"."Alias" AS "TASK_T_Alias", "TASK_T"."Type" AS "TASK_T_Type", "TASK_T"."CreatedTime" AS "TASK_T_CreatedTime" 
FROM "TASK_T" 
WHERE "TASK_T"."ID" = ?]
[parameters: (UUID('e918b3ca-7846-3104-8c4d-feb016a9e618'),)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
2023-01-02 00:37:48,506 db_manager_task INFO: regist Task ID:e918b3ca-7846-3104-8c4d-feb016a9e618
2023-01-02 00:37:48,621 server INFO: CELERY CFG: server.config.cfg_celery_local
2023-01-02 00:37:48,621 server INFO: Starting Flask Resource report Info...
2023-01-02 00:37:48,623 server INFO: Starting Flask App...
2023-01-02 00:40:53,344 db_manager INFO: DB create_all called
2023-01-02 00:40:53,346 db_manager_task INFO:  register_task in DB ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-02 00:40:53,346 db_manager_task INFO: {'alias': 'default', 'type': '0'}
2023-01-02 00:40:53,346 db_manager_task INFO: default
2023-01-02 00:40:53,352 db_manager_task ERROR: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT "TASK_T"."ID" AS "TASK_T_ID", "TASK_T"."Alias" AS "TASK_T_Alias", "TASK_T"."Type" AS "TASK_T_Type", "TASK_T"."CreatedTime" AS "TASK_T_CreatedTime" 
FROM "TASK_T" 
WHERE "TASK_T"."ID" = ?]
[parameters: (UUID('e918b3ca-7846-3104-8c4d-feb016a9e618'),)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
2023-01-02 00:40:53,352 db_manager_task INFO: regist Task ID:e918b3ca-7846-3104-8c4d-feb016a9e618
2023-01-02 00:40:53,463 server INFO: CELERY CFG: server.config.cfg_celery_local
2023-01-02 00:40:53,464 server INFO: Starting Flask Resource report Info...
2023-01-02 00:40:53,465 server INFO: Starting Flask App...
2023-01-02 01:02:34,052 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:02:34,052 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:02:44,057 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:02:44,057 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:02:53,588 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ?]
[parameters: ('SUCCESS',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:02:53,589 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 01:02:53,589 task_statustimer ERROR: TIMER REPORT update DB Exception:'NoneType' object is not iterable
2023-01-02 01:02:54,058 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:02:54,058 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:03:04,067 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:03:04,068 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:03:14,069 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:03:14,069 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:03:24,076 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:03:24,077 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:03:34,087 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:03:34,087 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:03:44,081 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:03:44,082 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:03:53,594 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ?]
[parameters: ('SUCCESS',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:03:53,594 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 01:03:53,595 task_statustimer ERROR: TIMER REPORT update DB Exception:'NoneType' object is not iterable
2023-01-02 01:03:54,087 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:03:54,087 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:04:04,089 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:04:04,089 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:04:14,098 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:04:14,098 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:04:24,098 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:04:24,098 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:04:34,102 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:04:34,102 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:04:44,109 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:04:44,109 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:04:53,602 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ?]
[parameters: ('SUCCESS',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:04:53,602 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 01:04:53,602 task_statustimer ERROR: TIMER REPORT update DB Exception:'NoneType' object is not iterable
2023-01-02 01:04:54,114 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:04:54,114 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:05:04,121 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:05:04,122 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:05:14,131 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:05:14,131 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:05:24,132 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:05:24,132 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:05:34,138 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:05:34,139 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:05:44,134 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:05:44,134 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:05:53,608 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ?]
[parameters: ('SUCCESS',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:05:53,609 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 01:05:53,609 task_statustimer ERROR: TIMER REPORT update DB Exception:'NoneType' object is not iterable
2023-01-02 01:05:54,137 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:05:54,137 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:06:04,138 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:06:04,138 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:06:14,145 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:06:14,145 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:06:24,157 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:06:24,158 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:06:34,162 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:06:34,162 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:06:44,160 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:06:44,161 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:06:53,601 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ?]
[parameters: ('SUCCESS',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:06:53,601 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 01:06:53,601 task_statustimer ERROR: TIMER REPORT update DB Exception:'NoneType' object is not iterable
2023-01-02 01:06:54,161 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:06:54,161 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:07:04,163 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:07:04,163 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:07:14,167 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:07:14,168 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:07:24,175 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:07:24,175 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:07:34,180 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:07:34,180 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:07:44,185 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:07:44,186 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:07:53,607 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ?]
[parameters: ('SUCCESS',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:07:53,608 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 01:07:53,608 task_statustimer ERROR: TIMER REPORT update DB Exception:'NoneType' object is not iterable
2023-01-02 01:07:54,186 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:07:54,187 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:08:04,199 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:08:04,200 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:08:14,204 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:08:14,205 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:08:24,208 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:08:24,208 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:08:34,216 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:08:34,217 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:08:44,218 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:08:44,218 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:08:53,618 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ?]
[parameters: ('SUCCESS',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:08:53,619 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 01:08:53,620 task_statustimer ERROR: TIMER REPORT update DB Exception:'NoneType' object is not iterable
2023-01-02 01:08:54,225 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:08:54,229 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:09:04,231 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:09:04,232 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:09:14,232 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:09:14,233 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:09:24,235 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:09:24,236 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:09:34,238 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:09:34,239 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:09:44,242 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:09:44,242 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:09:53,616 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ?]
[parameters: ('SUCCESS',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:09:53,617 db_manager_report INFO: query report by status SUCCESS : None
2023-01-02 01:09:53,617 task_statustimer ERROR: TIMER REPORT update DB Exception:'NoneType' object is not iterable
2023-01-02 01:09:54,246 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:09:54,247 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:10:04,253 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:10:04,254 db_manager_report INFO: query report by status START or REVOKING : None
2023-01-02 01:10:14,262 db_manager_report ERROR: (sqlite3.OperationalError) no such table: REPORT_T
[SQL: SELECT "REPORT_T"."CeleryTaskID" AS "REPORT_T_CeleryTaskID", "REPORT_T"."TaskID" AS "REPORT_T_TaskID", "REPORT_T"."TaskType" AS "REPORT_T_TaskType", "REPORT_T"."DeviceId" AS "REPORT_T_DeviceId", "REPORT_T"."QueueId" AS "REPORT_T_QueueId", "REPORT_T"."ContainerId" AS "REPORT_T_ContainerId", "REPORT_T"."ParameterList" AS "REPORT_T_ParameterList", "REPORT_T"."Status" AS "REPORT_T_Status", "REPORT_T"."Description" AS "REPORT_T_Description", "REPORT_T"."LogLocation" AS "REPORT_T_LogLocation", "REPORT_T"."ReportLocation" AS "REPORT_T_ReportLocation", "REPORT_T"."EmailReceiverList" AS "REPORT_T_EmailReceiverList", "REPORT_T"."Current" AS "REPORT_T_Current", "REPORT_T"."CeleryTaskStartTime" AS "REPORT_T_CeleryTaskStartTime", "REPORT_T"."StartRunTime" AS "REPORT_T_StartRunTime", "REPORT_T"."LastRunTime" AS "REPORT_T_LastRunTime", "REPORT_T"."FailedReason" AS "REPORT_T_FailedReason", "REPORT_T"."ResyncPath" AS "REPORT_T_ResyncPath", "REPORT_T"."TaskOwner" AS "REPORT_T_TaskOwner", "REPORT_T"."Group" AS "REPORT_T_Group" 
FROM "REPORT_T" 
WHERE "REPORT_T"."Status" = ? OR "REPORT_T"."Status" = ?]
[parameters: ('START', 'REVOKING')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-02 01:10:14,263 db_manager_report INFO: query report by status START or REVOKING : None
